### ISSUE TITLE
Error in discord logs

### ISSUE THREAD

**Issue by zachkont** [GameFeeder/GameFeeder#83]
The following error appeared in the logs 6 times

```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:178:17)
    at WebSocketConnection.onError (/home/zach/projects/valveGamesAnnouncerBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:374:17)
    at WebSocket.onError (/home/zach/projects/valveGamesAnnouncerBot/node_modules/discord.js/node_modules/ws/lib/event-target.js:128:16)
    at WebSocket.emit (events.js:189:13)
    at _receiver.cleanup (/home/zach/projects/valveGamesAnnouncerBot/node_modules/discord.js/node_modules/ws/lib/websocket.js:211:14)
    at Receiver.cleanup (/home/zach/projects/valveGamesAnnouncerBot/node_modules/discord.js/node_modules/ws/lib/receiver.js:557:13)
    at WebSocket.finalize (/home/zach/projects/valveGamesAnnouncerBot/node_modules/discord.js/node_modules/ws/lib/websocket.js:206:20)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at args.(anonymous function) (/home/zach/.config/yarn/global/node_modules/event-loop-inspector/index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by TimJentzsch** [comment]
I have not seen this error in a long time, I will close this for now.
